# Generated by Django 2.2.4 on 2020-06-25 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
