# Generated by Django 2.2.4 on 2020-06-27 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_content_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
